# Generated by Django 5.1.2 on 2024-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApertureScience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
