# Generated by Django 5.1.2 on 2024-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApertureScience', '0004_experiment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubject',
            name='image',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
