# Generated by Django 5.1.2 on 2024-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApertureScience', '0006_rename_products_experiment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
