# Generated by Django 5.1.2 on 2024-12-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApertureScience', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='publicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 13, 41, 28, 254785, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
